name: CI Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout source
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # define in repo settings
          password: ${{ secrets.DOCKER_SECRET }}    # define in repo settings

      # 4. Build & push backend image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./springbootexamproject
          file: ./springbootexamproject/backend.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ansible-labexam-backend:latest

      # 5. Build & push frontend image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./reactexamapp
          file: ./reactexamapp/frontend.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ansible-labexam-frontend:latest
